server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDb
    username: root
    password: saibaba@123
    # Optional but good practice for MySQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect  # Specify dialect explicitly
